version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: back_hares_db
    restart: always
    environment:
      POSTGRES_USER: hares_user
      POSTGRES_PASSWORD: hares_pass
      POSTGRES_DB: hares_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: back_hares_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=hares_user
      - POSTGRES_PASSWORD=hares_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hares_db
    depends_on:
      - db

volumes:
  postgres_data: